## Python: (not) solving the SP - circuit distance

Here we use a Python implementation of the method to solve the SP
that is based on diminishing the circuit distance.

First we import some code.
Note in particular the `solve_sp_fast` and `compass_d` functions from our companion [utils.py](utils.py) module,
and `nswap_generators` from the [generators.py](generators.py) module.

In [1]:
from timeit import timeit

import numpy as np

from utils import solve_sp_fast, compass_d
from generators import nswap_generators

Then we use it to sort some lists.
It is easy to see that most of the time,
we will find an index that does not correspond to the solution.

In [6]:
# create generator set

gens = nswap_generators(10)

# Check a few runs of the algorithm:

for _ in range(10):
    # Create a list of integers:
    S = np.arange(10)
    # Shuffle the list:
    np.random.shuffle(S)
    # run the algorithm
    solve_sp_fast(S, gens, compass_d)

[6 2 0 5 9 7 4 1 3 8]
[4 1 2 5 8 3 0 6 7 9]
[8 3 2 5 6 9 7 4 1 0]
[3 6 8 4 0 5 9 7 2 1]
[9 8 4 0 3 6 7 5 2 1]
[6 8 9 7 3 2 0 1 4 5]
[9 4 0 5 6 8 7 3 2 1]
[9 7 6 5 4 1 0 2 3 8]
[7 3 0 1 6 8 5 2 4 9]
[5 6 8 9 7 4 2 0 1 3]
