## Python: solving the SP - distance to monotonic index

Here we use a Python implementation of the method to solve the SP
that is based on diminishing the vector distance to an arbitrary monotonic distribution.

Given an ISP with $\mathbf{c} = |\mathbf{S}|$, we will just pick $[1..\mathbf{c}]$
as our target monotonic distribution.

First we import some code.
Note in particular the `solve_sp_fast` and `compass_m` functions from our companion [utils.py](utils.py) module,
and `nswap_generators` from the [generators.py](generators.py) module.

In [2]:
from timeit import timeit

import numpy as np

from utils import solve_sp_fast, compass_m
from generators import nswap_generators

Then we use it to sort some lists.
It is easy to see that as our lists get longer,
the performance suffers little.

In [3]:
# Create a list of integers:

S = np.arange(6)

# Shuffle the list:

np.random.shuffle(S)

# create generator set

gens = nswap_generators(6)

# Check the time our naive function takes to sort it:

timeit("solve_sp_fast(S, gens, compass_m)", number=1, globals=globals())

[0 1 2 3 4 5]


0.001579029019922018

Now with a list of 8 integers:

In [5]:
S = np.arange(8)

np.random.shuffle(S)

gens = nswap_generators(8)

timeit("solve_sp_fast(S, gens, compass_m)", number=1, globals=globals())

[0 1 2 3 4 5 6 7]


0.002316241036169231

And with a list of 10 integers:

In [6]:
S = np.arange(10)

np.random.shuffle(S)

gens = nswap_generators(10)

timeit("solve_sp_fast(S, gens, compass_m)", number=1, globals=globals())

[0 1 2 3 4 5 6 7 8 9]


0.003819979028776288

And finally 100 integers:

In [7]:
S = np.arange(100)

np.random.shuffle(S)

gens = nswap_generators(100)

timeit("solve_sp_fast(S, gens, compass_m)", number=1, globals=globals())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


2.3941782400361262